version: '3'
services:

  node1:
    image: cassandra:3.11
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1,node2
    restart: unless-stopped

  node2:
    image: cassandra:3.11
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1,node2
    restart: unless-stopped
